### ISSUE TITLE
Can't deploy due to node 6.x runtime

### ISSUE THREAD

**Issue by nason** [awslabs/real-time-insights-account-activity#4]
This template fails at `CustomResourceHelper` with this reason:

> The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;

**Comment by tanmaymohan** [comment]
Any update on this ?

Will fixing the CustomResourceHelper runtime value in the .template file help ?

**Comment by MarkAtwood** [comment]
Thanks for reporting this!  We are routing this issue to the tech team that may be able to address it.

**Comment by tanmaymohan** [comment]
I think it's just an outdated text , I tried renaming it and uploaded the .template file on the cloudformation page and this issue was solved.

**Comment by georgebearden** [comment]
Hi @tanmaymohan. Thank you for the update. I'm on the Solutions team that owns this solution. Shortly we will be updating this solution with both the node8 upgrade in addition to upgrading the solution to Python 3.7. I'll update this issue once its out. 

Thanks again!

**Comment by georgebearden** [comment]
Hi All - We just released an update to this solution that addresses this issue. You can grab the latest [CloudFormation template](https://s3.amazonaws.com/solutions-reference/real-time-insights-account-activity/latest/real-time-insights-account-activity.template) from the [Solutions Landing Page](https://aws.amazon.com/solutions/real-time-insights-account-activity/?did=sl_card&trk=sl_card).

Going to close this issue, but please re-open if you run into any other problems related to the node upgrade.
